### PR TITLE
Add React example

### PR DESCRIPTION
**Pull request by Aerlinger**
First steps for a working example in React. Includes integration with Webpack/Babel for compiling JSX code. See Readme for more details and steps to run.

### CODE REVIEW

**Comment by Aerlinger** [comment]
Note that the code runs, but for some reason styles aren't being loaded properly. I'm at a loss as to why:

image

**Comment by Aerlinger** [comment]
Note that this is still a work-in-progress. More will be coming soon, but wanted to share my progress so far.

**Comment by jwu** [comment]
Hi @Aerlinger 

Sorry for the late review. I think this example is too huge to people who just getting start. But it is a very good example for showing working with React. So I decide to create a new organization for it. 

Here it is: https://github.com/editor-framework/example-react. I've add you to it, so you can push this example on it. What do you think ?

**Comment by Aerlinger** [comment]
Hey @jwu, Sorry for the late response. I agree the example is a bit large, though I think most of the complexity here is from the Webpack + Babel dependency to compile the JSX. Would love to make working with React simpler. Any thoughts on how to accomplish this?

**Comment by Aerlinger** [comment]
@jwu Also, any thoughts as to why the styles aren't loading? See my comment above.

**Comment by jwu** [comment]
I haven't try React too much so I'm not sure what's the problem inside it. But based on our evaluation before, we found that React will not binding properties if you are using Custom Element. React treat element with `-` as Custom Element which lead to this problem.

Anyway, I will check your code in the new repo and see if I can figure out a way for it.

I will close this PR right now.

**Comment by Aerlinger** [comment]
> we found that React will not binding properties if you are using Custom Element

Not sure what you mean by this. Can you be more specific or show an example?

**Pull request closed without merging**
